name: Generate Pie Chart from PDF

on:
  workflow_dispatch:
    inputs:
      file_name:
        description: 'Name of the PDF file to upload'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install PyPDF2 matplotlib

    - name: Download PDF file
      uses: actions/download-artifact@v3
      with:
        name: uploaded_pdf
        path: ./

    - name: Rename file
      run: |
        mv uploaded_pdf.pdf ${{ github.event.inputs.file_name }}

    - name: Run script
      run: |
        python script.py "${{ github.event.inputs.file_name }}"

    - name: Upload Pie Chart
      uses: actions/upload-artifact@v4
      with:
        name: pie_chart
        path: pie_chart.png
