name: Process PDF and Generate Pie Chart

on:
  workflow_dispatch:
    inputs:
      file_name:
        description: 'Name of the PDF file to upload'
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Upload PDF file
      uses: actions/upload-artifact@v4
      with:
        name: uploaded_pdf
        path: path/to/your/pdf_file.pdf

  process:
    runs-on: ubuntu-latest
    needs: upload  # This ensures that the `upload` job is completed before this job starts
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download PDF file
      uses: actions/download-artifact@v4
      with:
        name: uploaded_pdf
        path: ./

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install PyPDF2 matplotlib

    - name: Rename file
      run: |
        mv "${{ github.event.inputs.file_name }}" uploaded_pdf.pdf

    - name: Run script
      run: |
        python script.py uploaded_pdf.pdf

    - name: Upload Pie Chart
      uses: actions/upload-artifact@v4
      with:
        name: pie_chart
        path: pie_chart.png
